GardeningTool/HostsMod

main.cpp

added another blocked site

---

README.md
src/main.cpp

steancomunnity.ru

---

README.md
src/main.cpp

streamcommunnlty.ru

---

domains.txt

They are getting in the big leagues: they got a .com domain

steamcommnuitry.com

---

domains.txt

Novo staff got ratted and the person who ratted them made novoline.wtf redirect to novoline.gg and everyone is saying it’s a rat

novoline.gg

---

domains.txt

streammcomunnity.ru

---

domains.txt

steamcommunytiy.ru

---

domains.txt

stearncommunytiy.ru

---

README.md

Just fixing a typo in README. Won't affect else.

nvmcentral.net?

---

domains.txt

strearncomuniity.ru.com

---

domains.txt

Here comes trouble

---

README.md

Make sure to improve it, it's trash rn.

Added a list of ratted cracks with proof

---

domains.txt

store-stempowered.com

---

domains.txt

I guess csgo isn’t trendy anymore, all the cool kids now playing rust

steamcommynitu.ru

---

domains.txt

discord-nitro.site

---

domains.txt

steamcommurnuity.com

---

domains.txt

back on that grind

---

domains.txt

free nitro 2: electric booagloo

---

domains.txt

seems like they gave up on steam scams and are moving on...

nitro free wtf

---

domains.txt

damn, i wish they lived near me so i could also get airdropped nitro 😔

discorcl.link

---

domains.txt

they finially did it, they finially pinged everyone

---

domains.txt

very good bot, set it to auto delete messages when people without permissions to ping everyone try to ping everyone, using that against them

discord-nitro.su

---

domains.txt

added sniffip cuz I see there are grabify links

---

domains.txt

Block Rise 5.100 r3 (AllahLeaks) RAT Domains
